# Generated by Django 4.0.1 on 2022-01-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamento_empresa'),
        ('funcionarios', '0002_alter_funcionario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='departamentos',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='departamentos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='departamentos.departamento'),
            preserve_default=False,
        ),
    ]
