# Generated by Django 4.0.1 on 2022-01-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extras', '0002_registrohoraextra_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
