# Generated by Django 4.0.1 on 2022-01-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extras', '0003_registrohoraextra_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registrohoraextra',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registrohoraextra',
            name='horas',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Horas trabalhadas'),
        ),
    ]
